---
tools:
  cat1:
    rules:
      - rule_type: file_size
        lower_bound: 16
        upper_bound: Infinity
        destination: vgl_1c
      default_destination: local_dest
  hifiasm:
    default_destination: dynamic_partition_cores
default_destination: vgl_32c
verbose: True